title: Ryan Huang
description: A Person Website For Ryan Huang
baseurl: ""
url: ryanhuang.xyz

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
