title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: ""
url: https://1bf0ff2c.ryan-huang1-github-io.pages.dev

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
